### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by NextRaven10** [Tater-Certified/LifeSteal#6] opened 2024-08-28 15:45 UTC
An Update to 1.21.1 would be greatly appreciated :D

**Comment by QPCrummer** [comment] 2024-08-28 15:50
I am working on a rewrite that will support 1.21.1

**Comment by QPCrummer** [comment] 2024-12-31 09:42
I’m closing this issue as the mod has moved on to MC 1.21.4. If there is a considerable amount of people wanting MC 1.21.1, I may backport version 2.0.0.

**Closed as completed by QPCrummer** 2024-12-31 09:42 UTC

**Comment by virtualspan** [comment] 2025-01-13 07:06
Just letting you know that there are more people who'd like a backport.

**Comment by virtualspan** [comment] 2025-01-13 07:07
1.21.1 is kind of like the "main minecraft version for mods" rn. Where basically most mods are supported while not sticking to 1.12.2. So updating to 1.21.4 would be a bit of a downgrade for my server. Which is why I'd like a backport for better mod compatibility.

**Comment by QPCrummer** [comment] 2025-01-13 20:55
@virtualspan 
This is a server-side mod, not really a content mod. A majority of server-side mods update as Mojang updates due to new features being added that we take advantage of. I can consider backporting to 1.21.1, however it would require a good deal of recoding due to gamerule and Polymer changes. If a get free time, I can backport it.

**Comment by virtualspan** [comment] 2025-01-14 01:10
Thanks, but just saying that many mods like Yung's mods or other structure and miscellaneous mods haven't updated yet, so while many mods have updated to 1.21.4, many still haven't even when just including serverside ones.

**Comment by QPCrummer** [comment] 2025-01-14 08:30
@virtualspan 
I have ported the latest 2.0.1 version to 1.21.1. I need people to test and make sure all features are working as intended. The source can be found on the `rewrite-1.21.1` branch.

**Comment by QPCrummer** [comment] 2025-01-14 08:30
[lifesteal-2.0.1.zip](https://github.com/user-attachments/files/18407538/lifesteal-2.0.1.zip)
Or here if you want it prebuilt

**Comment by virtualspan** [comment] 2025-01-15 03:59
Thank you so much.

**Comment by virtualspan** [comment] 2025-01-15 04:03
You're a legend bro

**Comment by QPCrummer** [comment] 2025-01-15 04:04
An updated version will be coming soon to fix issues @virtualspan

**Comment by virtualspan** [comment] 2025-01-15 04:23
ok
